server {
    listen 80;
    listen [::]:80;
    server_name o-mid.com www.o-mid.com;

    root /var/www/o-mid.com;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /resume/Omid_Mirzaei_CV.pdf {
        default_type application/pdf;
        add_header Content-Disposition 'inline; filename="Omid_Mirzaei_CV.pdf"';
        add_header Cache-Control "public, max-age=3600";
    }

    location ~* \.(css|js|jpg|jpeg|png|webp|svg|ico|pdf|wasm|otf|ttf|woff|woff2)$ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
